ktor:
    application:
        modules:
            - app.cesario.ApplicationKt.module
    deployment:
        port: "$PORT:9999"
        healthCheckUpdater: ${IS_HEALTH_CHECK_UPDATER:true}
        # Optimized for resource constraints
        maxConnections: 1000  # Reduced from 2000
        workerGroupSize: 4    # Reduced from 16 (0.6 cores = ~4 threads)
        callGroupSize: 8      # Reduced from 32
        connectionGroupSize: 4 # Reduced from 16
    services:
        redis:
            host: "$REDIS_HOST:localhost"
            port: "$REDIS_PORT:6379"
        default_processor:
            host: "$DEFAULT_PROCESSOR_HOST:localhost"
            port: "$DEFAULT_PROCESSOR_PORT:8001"
        fallback_processor:
            host: "$FALLBACK_PROCESSOR_HOST:localhost"
            port: "$FALLBACK_PROCESSOR_PORT:8002"
